"""n_documento unico

Revision ID: 482aaa8bb9cb
Revises: 52460df1bf33
Create Date: 2026-09-10 13:47:59.621791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482aaa8bb9cb'
down_revision: Union[str, Sequence[str], None] = '52460df1bf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documentos_n_documento', table_name='documentos')
    op.create_unique_constraint('uq_documentos_n_documento', 'documentos', ['n_documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documentos_n_documento', 'documentos', type_='unique')
    op.create_index('ix_documentos_n_documento', 'documentos', ['n_documento'], unique=False)
    # ### end Alembic commands ###
