"""crear tablas iniciales: usuarios y documentos

Revision ID: 52460df1bf33
Revises: 
Create Date: 2026-09-09 07:37:35.046679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52460df1bf33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('SECRETARIA', 'CONSULTA', 'ADMIN', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.Enum('SINOLE', 'FEDUNPE', name='entidadenum'), nullable=False),
    sa.Column('fecha_envio', sa.Date(), nullable=False),
    sa.Column('n_documento', sa.String(length=50), nullable=False),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('destinatario', sa.String(length=200), nullable=False),
    sa.Column('cc', sa.String(length=200), nullable=True),
    sa.Column('requiere_respuesta', sa.Boolean(), nullable=False),
    sa.Column('carta_reiterativa_enviada', sa.Boolean(), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('n_documento_respuesta', sa.String(length=50), nullable=True),
    sa.Column('asunto_respuesta', sa.Text(), nullable=True),
    sa.Column('responde', sa.String(length=200), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_entidad'), 'documentos', ['entidad'], unique=False)
    op.create_index(op.f('ix_documentos_n_documento'), 'documentos', ['n_documento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_n_documento'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_entidad'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
